# Generated by Django 6.0.1 on 2026-02-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destiination',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
